#!/usr/bin/perl
# :mode=perl:
# Debug

my $username       = substr(`whoami`,0,-1);
my $php_cgi_exec   = "/usr/bin/php"; 
my $ini_path       = "/home/$username/php-inis/"; 


# A small wrapper script to call PHP in cgi mode for suexec enabled servers
# drop this script into cgi-bin, and put the following in your root level .htaccess 
# 
# AddHandler .php php-cgiwrap
# Action php-cgiwrap /cgi-bin/php-cgiwrap.cgi
#
# This script has the following main advantage..
#  you may create a file /cgi-bin/php{version}-inis/site.ini
#  and include in that directives which will be merged with the system standard 
#  php.ini for the CGI binary.  This allows you to override certain settings...
#
# ------------ Example site.ini -- cut here --------------------
# ; Remove all Payflow Pro settings entirely (by removing the section)
# -[Verisign Payflow Pro]
#
# ; Remove the mssql.compatability_mode setting entirely
# -mssql.compatability_mode
#
# ; Set the mssql min_error_severity to 10, no matter what it was before
# mssql.min_error_severity=10
#
# ; Remove all ingres settings, but leave the section header
# -preg:ingres\..*
#
# ; Remove the pspell extention
# -extension=pspell.so
#
# ; Add the mysql extention if it hasn't already been added
# extension=mysql.so
# 
# ; And add some mysql settings 
# [MySQL]
# mysql.allow_persistent=On
# ----------------------------------------------------------------------


# Try and be smart if the PHP binary doesn't exist where we are told 
if(!-f $php_cgi_exec)
{
  $php_cgi_exec = '/usr/bin/php'; 
}

my $bin_path   = $ENV{SCRIPT_FILENAME};
   $bin_path   =~ s/\/[^\/]*$/\//;
  
my $master_ini   = $ini_path . 'master.ini';
my $our_ini      = $ini_path . 'php.ini';
my $override_ini = $ini_path . 'site.ini';

if(0)
{
  print "Content-Type: text/plain\n\n";
  print $ini_path;
  
  my $username = substr(`whoami`,0,-1);
  #chomp($username);
  print "You are: $username\n";
  print `sh -c set`;
  exit;
}

if(!-f $ini_path)
{
  mkdir($ini_path);
}

if(!-f $master_ini)
{
  # Find the master ini file for the PHP binary
  my $ini = qx/exec -c $php_cgi_exec -i/;
  if($ini =~ />(\/.*\.ini)/)
  {
    $ini = $1;
    symlink $ini, $master_ini;
  }
}

if(   (! -f $our_ini) 
   || (-M $our_ini > -M $master_ini)
   || (-f $override_ini && (-M $our_ini > -M $override_ini))
  )
{  
  my $s = "(?:(?: |\t)*)";
  my $ini_contents = `cat $master_ini`;
  $ini_contents =~ s/^;.*$//mg;     # Remove all comments 
  $ini_contents =~ s/^(?: |\t)*(.*?)(?: |\t)*$/\1/mg;      # Trim all leading/trailing space  
  $ini_contents =~ s/\r?\n/\n/g;    # Make sure no CR, just LF
  $ini_contents =~ s/(?: |\t)*=(?: |\t)*/=/g;   # Trim whitespace around equals
  
  if(-f $override_ini)
  {
    open OVRD, "<$override_ini";
    foreach $line (<OVRD>)
    {
      $line =~ s/^(?:(?: |\t)*)(.*?)(?:(?: |\t)*)$/\1/;      # Trim all leading/trailing space
      if($line =~ /^-((\[|preg:)?(.*?))$/)
      {                
        if($2 eq '[') # Remove a section
        {
          $ini_contents =~ s/\Q$1\E(?:[^\n]|\n[^\[])*//g; # Remove [Section] to next ^[ or end of file
        }
        elsif($2 eq 'preg:')
        {          
          $ini_contents =~ s/^$3(?: |\t)*(;.*)?$//mg; # Treat as a preg 
        }        
        else
        {
          my $m = $1;
          $m =~ s/(?:(?: |\t)*)=(?:(?: |\t)*)/=/; # Trim whitespace around the equals
          $ini_contents =~ s/^\Q$m\E((?:(?: |\t)*)\=.*)?(;.*)?$//mg; # Treat as a line to match
        }
      }
      else
      {
        # be careful that we don't put the same command with the same value in twice
        # this will stop us loading extentions twice
        my $m = $line;
        $m =~ s/(?:(?: |\t)*)=(?:(?: |\t)*)/=/; # Trim whitespace around the equals
        $ini_contents =~ s/^\Q$m\E((?:(?: |\t)*)\=.*)?(;.*)?$//mg; # Treat as a line to match          
        $ini_contents .= "\n" . $line; # insert the new one
      }
    }
    close OVRD;
  }
  
  $ini_contents =~ s/\n{2,}/\n/g;      # Remove multiple newlines (blank lines)
  
  $new_ini = '
  
;         ____  _____    _    ____     _____ ___ ____  ____ _____
; __/\__ |  _ \| ____|  / \  |  _ \   |  ___|_ _|  _ \/ ___|_   _| __/\__
; \    / | |_) |  _|   / _ \ | | | |  | |_   | || |_) \___ \ | |   \    /
; /_  _\ |  _ <| |___ / ___ \| |_| |  |  _|  | ||  _ < ___) || |   /_  _\
;   \/   |_| \_\_____/_/   \_\____/   |_|   |___|_| \_\____/ |_|     \/

; DO NOT EDIT THIS FILE
; ========================================================================
;
; If you need to make modifications, please place such ini settings in 
; the file called site.ini (in this same directory) and they will be
; MERGED into this file automatically.  The format of the site.ini
; file is the same as for a normal php.ini, with a few additions which allow
; you to remove settings.  Here is an example to show you how to do it...
;
; ------------ Example site.ini -- cut here --------------------
; ; Remove all Payflow Pro settings entirely (by removing the section)
; -[Verisign Payflow Pro]
;
; ; Remove the mssql.compatability_mode setting entirely
; -mssql.compatability_mode
;
; ; Set the mssql min_error_severity to 10, no matter what it was before
; mssql.min_error_severity=10
;
; ; Remove all ingres settings, but leave the section header
; -preg:ingres\..*
;
; ; Remove the pspell extention
; -extension=pspell.so
;
; ; Add the mysql extention if it hasn\'t already been added
; extension=mysql.so
; 
; ; And add some mysql settings 
; [MySQL]
; mysql.allow_persistent=On
; ----------------------------------------------------------------------
;
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
; *********** DO NOT MODIFY THIS FILE - DO NOT MODIFY THIS FILE **********
' . $ini_contents . '
cgi.fix_pathinfo = 1
';

  open OUTFILE, ">" . $our_ini;
  print OUTFILE $new_ini;
  close OUTFILE;  
}




# WARNING - We are specifying fix_pathinfo=1 this will correct the 
# paths for us (PHP_SELF, PATH_INFO, PATH_TRANSLATED, SCRIPT_NAME, SCRIPT_FILENAME
# HOWEVER: PHP_SELF will NOT have the PATH_INFO on the end of it
#  and it is the rewritten SELF (if you used mod_rewrite, the requested "file" is 
#  NOT PHP_SELF, but the end result of the rewrite is).
chdir $ini_path; # PHP4 doesn't really grock -c <inifile> so we chdir there so it finds it
exec $php_cgi_exec, "-c", $out_ini;
